---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---

##Additional Analyses

#define new groups for analysis
```{r}
 table(pp$photoperiodism) #count the instances of each type of photoperiodism present in data. The three main groups make up most data (sd, ld, na) while the other is primarily associated with sd.

pp$simple_photoperiodism <- as.character(pp$photoperiodism) #startnew column to simplify the types into fairly functional groups for easy analysis

pp$simple_photoperiodism[pp$simple_photoperiodism == "ad"] <- "other"
pp$simple_photoperiodism[pp$simple_photoperiodism == "id"] <- "other"
pp$simple_photoperiodism[pp$simple_photoperiodism == "ldsd"] <- "other"
pp$simple_photoperiodism[pp$simple_photoperiodism == "lsd"] <- "other"
pp$simple_photoperiodism[pp$simple_photoperiodism == "sld"] <- "other"
pp$simple_photoperiodism[pp$simple_photoperiodism == "yes"] <- "other"

table(pp$simple_photoperiodism) #double check other

data2 <- left_join(data, pp) #add new pp info
data2$sensitivity_yn <- NULL #remove redundant column
data2$simple_photoperiodism <- as.factor(data2$simple_photoperiodism) 
data2$simple_photoperiodism <- relevel(data2$simple_photoperiodism, "na")

#write.csv(data2, "./Data/data2.csv")
```

#original lm
```{r}
#data2 <- read.csv("./Data/data2.csv")

lm.photogroups<- lmer(doy ~ simple_photoperiodism*year + (1|species), data = data2) #create linear model

anova(lm.photogroups) #anova output

```

#repeat lm analyses without outlier
```{r}
data2_nooutlier <- data2 %>% filter(species != "Poa_pratensis")

lm.photogroups.nooutlier <- lmer(doy ~ simple_photoperiodism*year + (1|species), data = data2_nooutlier)

anova(lm.photogroups.nooutlier)

```

#repeat lm analyses with only ld and sd
```{r}
data2_ldsd <- data2 %>% filter(simple_photoperiodism != "na")

lm.photogroups.ldsd <- lmer(doy ~ simple_photoperiodism*year + (1|species), data = data2_ldsd)

anova(lm.photogroups.ldsd)

```

#repeat lm analyses without outlier or na
```{r}
data2_ldsd_nooutlier <- data2_nooutlier %>% filter(simple_photoperiodism != "na")

lm.photogroups.ldsd.noooutlier <- lmer(doy ~ simple_photoperiodism*year + (1|species), data = data2_ldsd_nooutlier)

anova(lm.photogroups.ldsd.noooutlier)

```
